// Generates a Supabase data migration that syncs already-seeded projects to the
// current data/seed-data.json: removes retired seed issues (e.g. the duplicate
// checklist items), updates existing seeded issues in place (preserving user
// answers in issue_states), inserts newly added seed issues, and rebuilds the
// issue-to-section links. Custom (user-created) issues are never touched.
//
// Usage: node scripts/generate_seed_sync_migration.mjs
// Then:  supabase db push
import fs from "node:fs";
import path from "node:path";

const seed = JSON.parse(fs.readFileSync(path.resolve("data", "seed-data.json"), "utf8"));

const q = (value) => (value === null || value === undefined || value === "" ? "null" : `'${String(value).replace(/'/g, "''")}'`);

const seededKeyPattern = "^(q|gap|decision|change|doc|check)-";

const issueRows = seed.issues
  .map((issue, index) =>
    `  (${[
      q(issue.id),
      q(issue.issueType),
      q(issue.priority || "medium"),
      q(issue.category || null),
      q(issue.title),
      q(issue.prompt || issue.title),
      q(issue.details || null),
      q(issue.provisionalAnswer || null),
      q(issue.source || null),
      `${q(JSON.stringify(issue.tags || []))}::jsonb`,
      index
    ].join(", ")})`
  )
  .join(",\n");

const linkRows = seed.issues
  .flatMap((issue) =>
    (issue.termSectionIds || []).map((sectionKey, position) => `  (${q(issue.id)}, ${q(sectionKey)}, ${position})`)
  )
  .join(",\n");

const sql = `-- Generated by scripts/generate_seed_sync_migration.mjs on ${new Date().toISOString()}
-- Syncs previously seeded projects to the current curated seed data.
begin;

create temporary table seed_issues (
  stable_key text primary key,
  issue_type text not null,
  priority text not null,
  category text,
  title text not null,
  prompt text,
  details text,
  provisional_answer text,
  source_label text,
  tags jsonb not null,
  sort_order integer not null
) on commit drop;

insert into seed_issues (stable_key, issue_type, priority, category, title, prompt, details, provisional_answer, source_label, tags, sort_order) values
${issueRows};

create temporary table seed_issue_sections (
  issue_stable_key text not null,
  section_stable_key text not null,
  position integer not null
) on commit drop;

insert into seed_issue_sections (issue_stable_key, section_stable_key, position) values
${linkRows};

-- 1. Remove seeded issues that are no longer part of the seed (the duplicate
--    Section 7 checklist items). Cascades clean up their links/states/events.
delete from public.issues i
where i.stable_key ~ '${seededKeyPattern}'
  and not exists (select 1 from seed_issues s where s.stable_key = i.stable_key);

-- 2. Update surviving seeded issues in place; issue_states (user answers) are
--    keyed by issue id and remain untouched.
update public.issues i
set issue_type = s.issue_type,
    priority = s.priority,
    category = s.category,
    title = s.title,
    prompt = s.prompt,
    details = s.details,
    provisional_answer = s.provisional_answer,
    source_label = s.source_label,
    tags = s.tags,
    sort_order = s.sort_order
from seed_issues s
where i.stable_key = s.stable_key;

-- 3. Insert seed issues that seeded projects are missing (new gap questions).
--    The create_initial_issue_state trigger creates their issue_states rows.
insert into public.issues (
  project_id, stable_key, issue_type, initial_status, priority, category,
  title, prompt, details, provisional_answer, source_label, tags, sort_order, created_by
)
select p.id, s.stable_key, s.issue_type, 'open', s.priority, s.category,
       s.title, s.prompt, s.details, s.provisional_answer, s.source_label, s.tags, s.sort_order, p.created_by
from public.projects p
cross join seed_issues s
where exists (
    select 1 from public.issues i
    where i.project_id = p.id and i.stable_key ~ '${seededKeyPattern}'
  )
  and not exists (
    select 1 from public.issues i
    where i.project_id = p.id and i.stable_key = s.stable_key
  );

-- 4. Rebuild clause links for all seeded issues from the curated assignments.
delete from public.issue_sections ls
using public.issues i
where ls.issue_id = i.id
  and i.stable_key in (select stable_key from seed_issues);

insert into public.issue_sections (project_id, issue_id, section_id, position)
select i.project_id, i.id, ds.id, l.position
from seed_issue_sections l
join public.issues i on i.stable_key = l.issue_stable_key
join public.document_sections ds
  on ds.project_id = i.project_id and ds.stable_key = l.section_stable_key;

commit;
`;

const stamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
const outPath = path.resolve("supabase", "migrations", `${stamp}_sync_seeded_issues.sql`);
fs.writeFileSync(outPath, sql, "utf8");
console.log(`Wrote ${outPath}`);
console.log(`Seed issues: ${seed.issues.length}, section links: ${seed.issues.reduce((n, i) => n + (i.termSectionIds || []).length, 0)}`);
