-- Generated by scripts/generate_seed_sync_migration.mjs on 2026-07-05T23:23:15.868Z
-- Syncs previously seeded projects to the current curated seed data.
begin;

create temporary table seed_issues (
  stable_key text primary key,
  issue_type text not null,
  priority text not null,
  category text,
  title text not null,
  prompt text,
  details text,
  provisional_answer text,
  source_label text,
  tags jsonb not null,
  sort_order integer not null
) on commit drop;

insert into seed_issues (stable_key, issue_type, priority, category, title, prompt, details, provisional_answer, source_label, tags, sort_order) values
  ('decision-1-use-separate-carryco', 'decision', 'high', 'Immediate decisions', 'Use separate CarryCo?', 'Use separate CarryCo?: choose between the listed approaches or draft a custom answer.', 'Pick based on complexity of carry allocations and future placement/sourcing partners.', 'Option A: No; split carry inside GP LLC.
Option B: Yes; fund-specific CarryCo/SponsorCo.
Comment: Pick based on complexity of carry allocations and future placement/sourcing partners.', 'Open-items memo - Section 5 immediate decisions', '["high-level"]'::jsonb, 0),
  ('decision-2-who-owns-manager-llc', 'decision', 'high', 'Immediate decisions', 'Who owns Manager LLC?', 'Who owns Manager LLC?: choose between the listed approaches or draft a custom answer.', 'Do not give fund-specific placement parties platform-wide management fee economics unless intended.', 'Option A: You/Zeke directly.
Option B: Sponsor HoldCo owns Manager.
Comment: Do not give fund-specific placement parties platform-wide management fee economics unless intended.', 'Open-items memo - Section 5 immediate decisions', '["high-level"]'::jsonb, 1),
  ('decision-3-fund-exemption-path', 'decision', 'high', 'Immediate decisions', 'Fund exemption path?', 'Fund exemption path?: choose between the listed approaches or draft a custom answer.', 'Depends on LP count and QP status.', 'Option A: 3(c)(1).
Option B: 3(c)(7).
Comment: Depends on LP count and QP status.', 'Open-items memo - Section 5 immediate decisions', '["high-level"]'::jsonb, 2),
  ('decision-4-offering-path', 'decision', 'high', 'Immediate decisions', 'Offering path?', 'Offering path?: choose between the listed approaches or draft a custom answer.', 'Depends on whether there is general solicitation and verification tolerance.', 'Option A: 506(b).
Option B: 506(c).
Comment: Depends on whether there is general solicitation and verification tolerance.', 'Open-items memo - Section 5 immediate decisions', '["high-level"]'::jsonb, 3),
  ('decision-5-capital-call-design', 'decision', 'high', 'Immediate decisions', 'Capital-call design?', 'Capital-call design?: choose between the listed approaches or draft a custom answer.', 'Secondary strategy likely needs the faster version.', 'Option A: Normal 10-20 business days.
Option B: Fast 3-5 business days plus emergency calls/reserves.
Comment: Secondary strategy likely needs the faster version.', 'Open-items memo - Section 5 immediate decisions', '["multi-clause"]'::jsonb, 4),
  ('decision-6-vehicle-flexibility', 'decision', 'high', 'Immediate decisions', 'Vehicle flexibility?', 'Vehicle flexibility?: choose between the listed approaches or draft a custom answer.', 'Need broad flexibility for weird vehicles.', 'Option A: Narrow direct-secondary only.
Option B: Broad SPV/tender/forward/blocker/holding vehicle flexibility.
Comment: Need broad flexibility for weird vehicles.', 'Open-items memo - Section 5 immediate decisions', '["multi-clause"]'::jsonb, 5),
  ('decision-7-placement-compensation-disclosure', 'decision', 'high', 'Immediate decisions', 'Placement compensation disclosure?', 'Placement compensation disclosure?: choose between the listed approaches or draft a custom answer.', 'Likely disclose categories in main docs; specifics in separate agreements.', 'Option A: Generic disclosure only.
Option B: Generic disclosure plus term-sheet disclosure of categories and offsets.
Comment: Likely disclose categories in main docs; specifics in separate agreements.', 'Open-items memo - Section 5 immediate decisions', '["multi-clause"]'::jsonb, 6),
  ('decision-8-successor-fund-restriction', 'decision', 'high', 'Immediate decisions', 'Successor fund restriction?', 'Successor fund restriction?: choose between the listed approaches or draft a custom answer.', 'Need carveouts and allocation policy.', 'Option A: Standard restriction until fully invested.
Option B: Carveouts for SPVs, feeders, co-invests, parallel vehicles, future vintages.
Comment: Need carveouts and allocation policy.', 'Open-items memo - Section 5 immediate decisions', '["multi-clause"]'::jsonb, 7),
  ('change-01-ability-to-give-conditional-carry-or-incentive-payments', 'drafting-change', 'high', 'Requested drafting changes', 'Ability to give conditional carry or incentive payments', 'Add a general authorization/disclosure provision.', 'Counsel notes / decisions: Need counsel to decide whether specific arrangements are Fund Expenses, Manager expenses, GP/carry sharing, management fee offsets, or side-letter matters. Also need broker-dealer/finder analysis for transaction-based or commitment-based compensation.', 'The Fund, General Partner, Manager, or their affiliates may enter into placement, referral, capital introduction, revenue-sharing, or carry-sharing arrangements with registered broker-dealers, placement agents, finders, consultants, strategic partners, or other persons, subject to applicable law. Such arrangements may include cash fees, expense reimbursements, management fee sharing, carried interest participation, or other economics, and may differ among placement parties.', 'Open-items memo - Section 4 requested drafting changes', '["addition-removal"]'::jsonb, 8),
  ('change-02-sourcing-origination-and-strategic-relationship-arrangements', 'drafting-change', 'high', 'Requested drafting changes', 'Sourcing, origination, and strategic relationship arrangements', 'Add a general authorization/disclosure provision.', 'Counsel notes / decisions: Need separate form agreements for buy-side capital formation and sell-side investment sourcing. Each agreement should specify authority limits, compensation, tail, confidentiality, conflicts, and securities-law compliance.', 'The Manager, GP, or affiliates may enter into sourcing, origination, consulting, brokerage, referral, or strategic relationship agreements with third parties in connection with identifying, sourcing, diligencing, acquiring, selling, or disposing of investments.', 'Open-items memo - Section 4 requested drafting changes', '["addition-removal"]'::jsonb, 9),
  ('change-03-investment-objectives-and-permitted-investments', 'drafting-change', 'high', 'Requested drafting changes', 'Investment objectives and permitted investments', 'Revise the generic investment objective to cover these categories.', 'Counsel notes / decisions: The mandate should be broad enough to handle private secondary-market mechanics but narrow enough that LPs understand the strategy. Include a whitelist schedule and a process for adding/removing companies.', 'Late-stage private technology companies; secondary purchases; tender offers; direct secondaries; SPV interests; forward/contractual interests, if desired; whitelisted companies; private-market transfer restrictions; ROFR / company consent; fast-moving allocation opportunities.', 'Open-items memo - Section 4 requested drafting changes', '["addition-removal"]'::jsonb, 10),
  ('change-04-restriction-on-blind-pool-fund-investments-carveouts-for-weird-vehicle', 'drafting-change', 'high', 'Requested drafting changes', 'Restriction on blind-pool fund investments - carveouts for weird vehicles', 'Modify the blind-pool or fee-bearing vehicle restriction to preserve execution flexibility.', 'Counsel notes / decisions: Keep the LP-protective goal of avoiding fee layering into unrelated blind pools, but carve out normal secondary-access vehicles and structures needed to acquire private-company exposure.', 'Single-asset SPVs; co-investment vehicles; secondary-access vehicles; tender-offer vehicles; alternative investment vehicles; holding vehicles; feeder/blocker vehicles; vehicles formed to hold one or more specified whitelisted companies.', 'Open-items memo - Section 4 requested drafting changes', '["addition-removal"]'::jsonb, 11),
  ('change-05-capital-call-timing-and-fast-execution-mechanics', 'drafting-change', 'high', 'Requested drafting changes', 'Capital call timing and fast execution mechanics', 'Revise capital-call and funding mechanics to allow faster execution.', 'Counsel notes / decisions: The standard 10/15/20 business day capital call options may be too slow for secondary allocations. Need a practical process for LOIs, deposits, proof of funds, and warehoused positions.', 'Initial drawdown at closing, e.g. 10-25%; short capital-call period, e.g. 3-5 business days; emergency/special call period for time-sensitive deals; bridge facility or subscription line; GP advance rights; warehousing rights; reserves for deposits and broken-deal expenses.', 'Open-items memo - Section 4 requested drafting changes', '["addition-removal"]'::jsonb, 12),
  ('change-06-successor-funds-parallel-funds-co-invests-and-spv-carveouts', 'drafting-change', 'high', 'Requested drafting changes', 'Successor funds, parallel funds, co-invests, and SPV carveouts', 'Revise the successor-fund restriction and pair it with allocation rules.', 'Counsel notes / decisions: Need to balance LP protection against the need to move quickly and structure around specific secondary opportunities. Also pair this with a clear allocation policy.', 'Permit feeder vehicles, blocker vehicles, alternative investment vehicles, holding vehicles, parallel funds, co-investment vehicles, single-deal SPVs, overflow vehicles, and vehicles formed for tax, regulatory, business, allocation, or deal-execution reasons.', 'Open-items memo - Section 4 requested drafting changes', '["addition-removal"]'::jsonb, 13),
  ('q-001-will-the-fund-be-a-delaware-lp-or-delaware-llc', 'question', 'high', 'A. Entity structure and ownership', 'Will the fund be a Delaware LP or Delaware LLC', 'Will the fund be a Delaware LP or Delaware LLC?', 'The Orrick form assumes a Delaware LP governed by an LPA with a GP LLC. Choosing an LLC fund instead changes governance, tax boilerplate, and every Partner/Partnership reference, so settle this before any other drafting.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 14),
  ('q-002-will-the-gp-be-fund-specific-for-each-fund', 'question', 'medium', 'A. Entity structure and ownership', 'Will the GP be fund-specific for each fund', 'Will the GP be fund-specific for each fund?', 'A fund-specific GP is market standard: it isolates liability and carry per vintage and simplifies Fund II. A shared GP saves one entity but entangles the funds'' economics and liabilities.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 15),
  ('q-003-will-there-be-a-single-platform-manager-llc-across-all-funds', 'question', 'medium', 'A. Entity structure and ownership', 'Will there be a single platform Manager LLC across all funds', 'Will there be a single platform Manager LLC across all funds?', 'A single platform Manager is the usual pattern: it is the registered/exempt adviser and collects the management fee from each fund under an investment management agreement.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 16),
  ('q-004-will-there-be-a-sponsor-holdco-above-the-manager-and-gp-entities', 'question', 'low', 'A. Entity structure and ownership', 'Will there be a Sponsor HoldCo above the Manager and GP entities', 'Will there be a Sponsor HoldCo above the Manager and GP entities?', 'A HoldCo mainly helps if outside owners or several principals need platform-level economics. For a two-principal Fund I it usually just adds an entity.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 17),
  ('q-005-do-we-need-a-fund-specific-carryco-sponsorco-or-can-carry-be-split-in-', 'question', 'high', 'A. Entity structure and ownership', 'Do we need a fund-specific CarryCo/SponsorCo, or can carry be split in the GP LLC operating agreement', 'Do we need a fund-specific CarryCo/SponsorCo, or can carry be split in the GP LLC operating agreement?', 'Carry can be split inside the GP LLC operating agreement. A separate CarryCo is cleaner when non-voting participants, conditional/vested awards, or clawback sharing among recipients are expected - all likely here given placement and sourcing carry.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 18),
  ('q-006-if-carryco-is-used-does-it-own-the-gp-llc-or-merely-receive-carry-econ', 'question', 'medium', 'A. Entity structure and ownership', 'If CarryCo is used, does it own the GP LLC or merely receive carry economics from the GP', 'If CarryCo is used, does it own the GP LLC or merely receive carry economics from the GP?', 'Economics-only participation keeps control with the principals; ownership of the GP moves governance too. Most sponsors keep CarryCo as an economics vehicle only.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 19),
  ('q-007-who-has-voting-control-at-each-level-gp-manager-sponsor-holdco-carryco', 'question', 'medium', 'A. Entity structure and ownership', 'Who has voting control at each level: GP, Manager, Sponsor HoldCo, CarryCo', 'Who has voting control at each level: GP, Manager, Sponsor HoldCo, CarryCo?', 'Map control before granting anyone economics. LPs will also care: the removal-of-GP clause interacts with who actually controls the GP entity.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 20),
  ('q-008-can-non-voting-economic-participants-receive-carry-without-governance-', 'question', 'medium', 'A. Entity structure and ownership', 'Can non-voting economic participants receive carry without governance rights', 'Can non-voting economic participants receive carry without governance rights?', 'Yes, if the GP LLC or CarryCo agreement creates a non-voting economic class. Confirm securities-law treatment of granting those interests, especially to placement parties.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 21),
  ('q-009-how-are-clawback-obligations-allocated-among-ultimate-carry-recipients', 'question', 'high', 'A. Entity structure and ownership', 'How are clawback obligations allocated among ultimate carry recipients', 'How are clawback obligations allocated among ultimate carry recipients?', 'The Fund-level clawback sits on the GP; the GP/CarryCo agreement must push it through to every carry recipient (escrow, holdback, or several guarantee), or the principals end up covering departed participants'' share. Also settle the mechanics: the form tests the clawback only at wind-up, but if the waterfall is deal-by-deal LPs will push for interim clawback tests, an after-tax calculation, and escrow or personal guarantees from carry recipients.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 22),
  ('q-014-will-placement-fees-organization-expenses-transaction-fees-or-monitori', 'question', 'medium', 'B. Fund economics', 'Will placement fees, organization expenses, transaction fees, or monitoring fees offset management fees', 'Will placement fees, organization expenses, transaction fees, or monitoring fees offset management fees?', 'The offset section is optional in the form. Decide offsets now because they determine whether placement and sourcing costs are ultimately borne by LPs or by the Manager. Pair this with a cap on organizational and offering expenses borne by the fund (commonly $250k-$1M depending on size, excess borne by the Manager) - the form currently charges formation costs to the fund without a stated cap.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 23),
  ('q-017-european-waterfall-or-deal-by-deal-waterfall', 'question', 'high', 'B. Fund economics', 'European waterfall or deal-by-deal waterfall', 'European waterfall or deal-by-deal waterfall?', 'Deal-by-deal pays carry earlier but makes the clawback provision do real work; whole-fund (European) is more LP-friendly and simpler to administer.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 24),
  ('q-019-what-is-the-gp-commitment-and-can-it-be-cashless-notes-warehoused-secu', 'question', 'high', 'B. Fund economics', 'What is the GP commitment, and can it be cashless, notes, warehoused securities, or fee waiver', 'What is the GP commitment, and can it be cashless, notes, warehoused securities, or fee waiver?', 'The form''s Sponsor Capital Commitment already brackets cash, cashless, warehoused securities, and notes. Confirm the percentage (1-2% is common) and which funding forms LPs will accept.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 25),
  ('q-020-what-counts-as-a-late-stage-private-technology-company', 'question', 'high', 'C. Investment mandate and whitelist', 'What counts as a late-stage private technology company', 'What counts as a late-stage private technology company?', 'Define objectively (e.g., minimum valuation, revenue stage, or named-list approach) so compliance with the mandate is checkable at deal time.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 26),
  ('q-021-will-the-fund-be-limited-to-a-schedule-a-whitelist-of-companies', 'question', 'high', 'C. Investment mandate and whitelist', 'Will the fund be limited to a Schedule A whitelist of companies', 'Will the fund be limited to a Schedule A whitelist of companies?', 'A whitelist makes the blind pool much easier to market but constrains execution; pair it with a defined process to amend the schedule.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 27),
  ('q-022-who-can-add-or-remove-whitelist-companies-and-with-what-approval', 'question', 'medium', 'C. Investment mandate and whitelist', 'Who can add or remove whitelist companies, and with what approval', 'Who can add or remove whitelist companies, and with what approval?', 'Typical design: GP proposes, LPAC approves additions; removals unrestricted. Avoid requiring full LP amendment consent for routine list changes.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 28),
  ('q-023-can-the-fund-invest-in-companies-outside-the-whitelist-with-lpac-or-ma', 'question', 'medium', 'C. Investment mandate and whitelist', 'Can the fund invest in companies outside the whitelist with LPAC or majority LP approval', 'Can the fund invest in companies outside the whitelist with LPAC or majority LP approval?', 'An LPAC-approved exception path preserves flexibility without an amendment; decide the approval threshold and any basket size.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 29),
  ('q-024-can-the-fund-invest-in-spv-interests-tender-vehicles-forward-contracts', 'question', 'high', 'C. Investment mandate and whitelist', 'Can the fund invest in SPV interests, tender vehicles, forward contracts, contractual rights, or secondary-access vehicles', 'Can the fund invest in SPV interests, tender vehicles, forward contracts, contractual rights, or secondary-access vehicles?', 'Core to the strategy: the mandate and the investment limitations must both expressly permit indirect exposure instruments, or every secondary deal risks a consent process.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 30),
  ('q-025-can-the-fund-invest-in-non-u-s-companies-or-non-u-s-holding-structures', 'question', 'medium', 'C. Investment mandate and whitelist', 'Can the fund invest in non-U.S. companies or non-U.S. holding structures', 'Can the fund invest in non-U.S. companies or non-U.S. holding structures?', 'If yes, the vehicles section should permit blockers/feeders for tax reasons and the PPM needs non-U.S. risk and withholding disclosure.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 31),
  ('q-027-will-the-fund-allow-follow-on-investments-after-the-investment-period', 'question', 'medium', 'C. Investment mandate and whitelist', 'Will the fund allow follow-on investments after the investment period', 'Will the fund allow follow-on investments after the investment period?', 'The Investment Period section should carve out follow-ons and pending transactions; decide any cap on post-period follow-on capital.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 32),
  ('q-028-will-there-be-sector-exclusions-or-esg-prohibited-activity-restriction', 'question', 'low', 'C. Investment mandate and whitelist', 'Will there be sector exclusions or ESG/prohibited activity restrictions', 'Will there be sector exclusions or ESG/prohibited activity restrictions?', 'Often handled in side letters rather than fund-wide restrictions; decide the baseline now so side-letter asks are manageable.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 33),
  ('q-029-how-should-transfer-restrictions-rofrs-company-consent-tender-rules-an', 'question', 'medium', 'C. Investment mandate and whitelist', 'How should transfer restrictions, ROFRs, company consent, tender rules, and lockups be disclosed', 'How should transfer restrictions, ROFRs, company consent, tender rules, and lockups be disclosed?', 'These are portfolio-level execution risks unique to secondaries: disclose in the PPM risk factors and reflect in the valuation policy, since ROFRs and consent rights can break signed deals.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 34),
  ('q-032-what-is-the-emergency-special-capital-call-notice-period-for-time-sens', 'question', 'high', 'D. Capital calls, speed, and warehousing', 'What is the emergency/special capital call notice period for time-sensitive secondary deals', 'What is the emergency/special capital call notice period for time-sensitive secondary deals?', 'Add an expedited call (e.g., 3-5 business days) for identified transactions, paired with the bridge facility and GP-advance mechanics as a backstop.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 35),
  ('q-033-can-the-gp-call-capital-for-deposits-broken-deal-expenses-legal-dilige', 'question', 'medium', 'D. Capital calls, speed, and warehousing', 'Can the GP call capital for deposits, broken-deal expenses, legal diligence, and reserves', 'Can the GP call capital for deposits, broken-deal expenses, legal diligence, and reserves?', 'Make sure the call mechanics and the Fund Expenses definition both cover deposits and broken-deal costs, which are routine in competitive secondary processes.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 36),
  ('q-034-what-default-remedies-apply-if-an-lp-misses-a-capital-call', 'question', 'medium', 'D. Capital calls, speed, and warehousing', 'What default remedies apply if an LP misses a capital call', 'What default remedies apply if an LP misses a capital call?', 'The form leaves remedies to the fund agreement. Standard menu: interest on late amounts, dilution/forfeiture up to 50%, forced transfer, and loss of voting rights.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 37),
  ('q-035-can-the-fund-borrow-under-a-bridge-facility-or-subscription-line', 'question', 'medium', 'D. Capital calls, speed, and warehousing', 'Can the fund borrow under a bridge facility or subscription line', 'Can the fund borrow under a bridge facility or subscription line?', 'The form permits borrowing subject to a bracketed cap tied to commitments or uncalled commitments. Pick the cap (commonly 20-30% of commitments) and decide whether guarantees and leverage at SPV or holding-vehicle level count against it - with deals executed through SPVs, a fund-level-only cap is meaningless. Fund borrowing can also create UBTI for tax-exempt LPs.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 38),
  ('q-036-can-the-gp-or-affiliate-advance-funds-to-the-fund', 'question', 'medium', 'D. Capital calls, speed, and warehousing', 'Can the GP or affiliate advance funds to the fund', 'Can the GP or affiliate advance funds to the fund?', 'GP advances are the fastest bridge for a closing deadline. Authorize them expressly, with interest at cost and repayment from the next call to avoid a conflicts fight later.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 39),
  ('q-037-can-the-gp-or-affiliate-warehouse-securities-and-later-sell-them-to-th', 'question', 'high', 'D. Capital calls, speed, and warehousing', 'Can the GP or affiliate warehouse securities and later sell them to the fund', 'Can the GP or affiliate warehouse securities and later sell them to the fund?', 'The form''s optional Warehoused Securities clause permits transfers at cost plus expenses. Keep it - warehousing is core to executing before the fund closes - and decide whether warehoused positions can satisfy the GP commitment.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 40),
  ('q-038-what-approvals-are-needed-for-warehoused-investments', 'question', 'medium', 'D. Capital calls, speed, and warehousing', 'What approvals are needed for warehoused investments', 'What approvals are needed for warehoused investments?', 'Affiliate sales to the fund are classic conflict territory: decide whether cost-plus-expenses transfers within a set window are pre-authorized or need LPAC sign-off.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 41),
  ('q-039-how-are-warehousing-costs-interest-legal-fees-and-conflict-disclosures', 'question', 'medium', 'D. Capital calls, speed, and warehousing', 'How are warehousing costs, interest, legal fees, and conflict disclosures handled', 'How are warehousing costs, interest, legal fees, and conflict disclosures handled?', 'Define the transfer price formula (cost plus carrying costs at a stated rate) and disclose the arrangement in the PPM conflicts section.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 42),
  ('q-040-who-can-solicit-lps', 'question', 'high', 'E. Buy-side placement / capital formation', 'Who can solicit LPs', 'Who can solicit LPs?', 'Principals and Manager personnel can solicit under the issuer exemption; anyone compensated for raising capital raises broker-dealer issues. Inventory the expected placement parties before signing anything.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 43),
  ('q-041-must-any-compensated-lp-placement-be-through-a-registered-broker-deale', 'question', 'high', 'E. Buy-side placement / capital formation', 'Must any compensated LP placement be through a registered broker-dealer', 'Must any compensated LP placement be through a registered broker-dealer?', 'Transaction-based compensation to an unregistered finder is the classic foot-fault; the safe default is BD-only for success-fee arrangements.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 44),
  ('q-042-can-non-bd-finders-or-consultants-be-used-and-under-what-restrictions', 'question', 'medium', 'E. Buy-side placement / capital formation', 'Can non-BD finders or consultants be used, and under what restrictions', 'Can non-BD finders or consultants be used, and under what restrictions?', 'Only with flat-fee/consulting structures that avoid transaction-based pay, no negotiation role, and counsel sign-off. Document the analysis per relationship.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 45),
  ('q-043-can-placement-compensation-include-cash-fees-management-fee-sharing-ca', 'question', 'medium', 'E. Buy-side placement / capital formation', 'Can placement compensation include cash fees, management fee sharing, carried interest, revenue share, or expense reimbursement', 'Can placement compensation include cash fees, management fee sharing, carried interest, revenue share, or expense reimbursement?', 'Carry-sharing is usually the cleanest for non-BD parties because it is an internal GP/CarryCo split rather than a fund-paid fee, but it still needs conflicts disclosure and BD analysis if tied to commitments raised.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 46),
  ('q-044-is-compensation-paid-by-the-fund-gp-manager-carryco-or-affiliate', 'question', 'medium', 'E. Buy-side placement / capital formation', 'Is compensation paid by the Fund, GP, Manager, CarryCo, or affiliate', 'Is compensation paid by the Fund, GP, Manager, CarryCo, or affiliate?', 'Who pays determines who bears the cost: Fund-paid placement fees are LP money (and often trigger a fee offset); Manager/GP-paid comes out of sponsor economics.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 47),
  ('q-045-is-the-compensation-treated-as-fund-expense-manager-expense-or-gp-carr', 'question', 'medium', 'E. Buy-side placement / capital formation', 'Is the compensation treated as Fund Expense, Manager expense, or GP/carry sharing', 'Is the compensation treated as Fund Expense, Manager expense, or GP/carry sharing?', 'Keep the term sheet, LPA expense section, and offset provision consistent - LPs read all three, and mismatches invite negotiation.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 48),
  ('q-046-will-placement-linked-carry-require-disclosure-in-the-ppm-and-or-term-', 'question', 'medium', 'E. Buy-side placement / capital formation', 'Will placement-linked carry require disclosure in the PPM and/or term sheet', 'Will placement-linked carry require disclosure in the PPM and/or term sheet?', 'Disclose the category of arrangement (carry sharing with placement parties) in the PPM conflicts/fees sections; specific splits can stay in the separate agreements.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 49),
  ('q-047-will-placement-parties-receive-a-tail-on-lps-introduced-before-termina', 'question', 'low', 'E. Buy-side placement / capital formation', 'Will placement parties receive a tail on LPs introduced before termination', 'Will placement parties receive a tail on LPs introduced before termination?', 'A tail is a placement-agreement term, not a fund-document term; decide the standard tail (commonly 6-12 months) for the form agreement.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 50),
  ('q-048-who-approves-offering-materials-and-investor-communications', 'question', 'low', 'E. Buy-side placement / capital formation', 'Who approves offering materials and investor communications', 'Who approves offering materials and investor communications?', 'The Manager should have sole authority over offering materials, with placement parties contractually barred from creating their own.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 51),
  ('q-049-how-will-506-b-relationship-rules-or-506-c-verification-rules-be-handl', 'question', 'high', 'E. Buy-side placement / capital formation', 'How will 506(b) relationship rules or 506(c) verification rules be handled', 'How will 506(b) relationship rules or 506(c) verification rules be handled?', '506(b) requires pre-existing relationships and no general solicitation; 506(c) allows solicitation but requires accreditation verification. Placement-party outreach practices must match whichever path is chosen.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 52),
  ('q-050-who-can-source-secondary-opportunities', 'question', 'medium', 'F. Sell-side sourcing / origination', 'Who can source secondary opportunities', 'Who can source secondary opportunities?', 'Anyone can introduce deals; the design question is who may be compensated and how. Keep investment authority with the GP regardless of source.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 53),
  ('q-051-can-sourcing-parties-receive-cash-fees-deal-by-deal-carry-fund-carry-o', 'question', 'high', 'F. Sell-side sourcing / origination', 'Can sourcing parties receive cash fees, deal-by-deal carry, fund carry, or revenue share', 'Can sourcing parties receive cash fees, deal-by-deal carry, fund carry, or revenue share?', 'Deal-by-deal carry to a source is a fund-economics event that needs waterfall or GP-split plumbing; cash success fees raise BD issues if tied to securities transactions.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 54),
  ('q-052-can-a-deal-source-negotiate-terms-or-only-introduce-opportunities', 'question', 'medium', 'F. Sell-side sourcing / origination', 'Can a deal source negotiate terms, or only introduce opportunities', 'Can a deal source negotiate terms, or only introduce opportunities?', 'Introduction-only keeps the source on the safer side of the broker-dealer line; negotiation authority plus success comp looks like brokerage.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 55),
  ('q-053-can-a-deal-source-also-represent-sellers', 'question', 'medium', 'F. Sell-side sourcing / origination', 'Can a deal source also represent sellers', 'Can a deal source also represent sellers?', 'Dual representation is a live conflict: require disclosure, and decide whether LPAC consent is needed when a compensated source is on both sides.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 56),
  ('q-054-do-deal-source-payments-create-broker-dealer-concerns', 'question', 'high', 'F. Sell-side sourcing / origination', 'Do deal-source payments create broker-dealer concerns', 'Do deal-source payments create broker-dealer concerns?', 'Yes if compensation is transaction-based and the source effects securities transactions. This is a counsel sign-off item for each sourcing agreement, not a one-time decision.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 57),
  ('q-055-are-sourcing-fees-fund-expenses-or-manager-gp-expenses', 'question', 'medium', 'F. Sell-side sourcing / origination', 'Are sourcing fees Fund Expenses or Manager/GP expenses', 'Are sourcing fees Fund Expenses or Manager/GP expenses?', 'The form''s GP Expenses section brackets whether investment-sourcing costs sit with the sponsor. Decide the default and mirror it in the sourcing form agreement.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 58),
  ('q-056-are-there-exclusivity-non-circumvention-or-tail-periods', 'question', 'low', 'F. Sell-side sourcing / origination', 'Are there exclusivity, non-circumvention, or tail periods', 'Are there exclusivity, non-circumvention, or tail periods?', 'These live in the sourcing agreement; set house-standard positions (no exclusivity, narrow non-circumvention, short tail) for the template.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 59),
  ('q-057-what-disclosures-are-required-for-affiliated-or-related-party-sourcing', 'question', 'medium', 'F. Sell-side sourcing / origination', 'What disclosures are required for affiliated or related-party sourcing', 'What disclosures are required for affiliated or related-party sourcing?', 'Affiliate-sourced deals should be disclosed in the PPM conflicts section and may need LPAC consent under the investment limitations.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 60),
  ('q-058-how-are-conflicts-handled-if-a-source-also-participates-in-another-veh', 'question', 'medium', 'F. Sell-side sourcing / origination', 'How are conflicts handled if a source also participates in another vehicle', 'How are conflicts handled if a source also participates in another vehicle?', 'Combine allocation-policy treatment with LPAC disclosure: a source with its own SPV competing for the same allocation is the main real-world scenario.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 61),
  ('q-059-who-has-authority-to-approve-sourced-deals', 'question', 'medium', 'F. Sell-side sourcing / origination', 'Who has authority to approve sourced deals', 'Who has authority to approve sourced deals?', 'The GP''s investment committee approves all deals; sources never hold approval rights. Only conflicted deals escalate to the LPAC.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 62),
  ('q-060-when-can-a-successor-fund-be-launched', 'question', 'high', 'G. Future funds, SPVs, and allocations', 'When can a successor fund be launched', 'When can a successor fund be launched?', 'The form restricts successor blind pools during the investment period until a deployment threshold (often 70-75% invested/reserved). Pick the threshold and confirm SPVs don''t count as successor funds.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 63),
  ('q-061-what-counts-as-a-prohibited-substantially-similar-blind-pool-fund', 'question', 'medium', 'G. Future funds, SPVs, and allocations', 'What counts as a prohibited substantially similar blind-pool fund', 'What counts as a prohibited substantially similar blind-pool fund?', 'Define narrowly: a multi-investor blind pool with a substantially overlapping mandate. Single-deal SPVs, co-invests, and feeders should be expressly excluded.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 64),
  ('q-062-what-carveouts-are-needed-for-co-invest-vehicles-single-deal-spvs-feed', 'question', 'high', 'G. Future funds, SPVs, and allocations', 'What carveouts are needed for co-invest vehicles, single-deal SPVs, feeders, blockers, alternative investment vehicles, holding vehicles, and overflow vehicles', 'What carveouts are needed for co-invest vehicles, single-deal SPVs, feeders, blockers, alternative investment vehicles, holding vehicles, and overflow vehicles?', 'List every execution-vehicle type as an express carveout from the successor-fund restriction; this is the memo''s core drafting request and the biggest execution risk if missed.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 65),
  ('q-063-can-the-manager-manage-multiple-funds-at-once', 'question', 'medium', 'G. Future funds, SPVs, and allocations', 'Can the Manager manage multiple funds at once', 'Can the Manager manage multiple funds at once?', 'The form already permits other competitive activity; make sure the Manager''s other mandates only trip the restriction if they are substantially similar blind pools.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 66),
  ('q-064-how-are-opportunities-allocated-among-fund-i-fund-ii-co-invests-parall', 'question', 'high', 'G. Future funds, SPVs, and allocations', 'How are opportunities allocated among Fund I, Fund II, co-invests, parallel funds, SPVs, affiliates, and insiders', 'How are opportunities allocated among Fund I, Fund II, co-invests, parallel funds, SPVs, affiliates, and insiders?', 'Adopt a written allocation policy (fund-first with capacity-based overflow to co-invest/SPVs is typical) and reference it in the PPM; regulators and LPs both ask for it.', null, 'Open-items memo - Section 3 detailed questions', '["addition-removal"]'::jsonb, 67),
  ('q-065-can-lps-get-co-investment-rights', 'question', 'medium', 'G. Future funds, SPVs, and allocations', 'Can LPs get co-investment rights', 'Can LPs get co-investment rights?', 'The form keeps co-invest offers discretionary. Hold that line in the LPA and grant any priority rights through side letters so MFN exposure is controlled.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 68),
  ('q-066-can-insiders-invest-personally-alongside-the-fund', 'question', 'medium', 'G. Future funds, SPVs, and allocations', 'Can insiders invest personally alongside the fund', 'Can insiders invest personally alongside the fund?', 'Permit only after the fund takes its full allocation, with conflicts disclosure; unconstrained insider co-investment is a common LP diligence objection.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 69),
  ('q-067-can-the-fund-invest-through-a-vehicle-that-charges-its-own-fees-carry', 'question', 'medium', 'G. Future funds, SPVs, and allocations', 'Can the fund invest through a vehicle that charges its own fees/carry', 'Can the fund invest through a vehicle that charges its own fees/carry?', 'Secondary access often requires buying into fee-bearing SPVs. Permit it with a cap or LPAC consent, and disclose the fee layering; a flat prohibition would block core strategy deals.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 70),
  ('q-068-will-lpac-approval-be-needed-for-certain-conflicts-or-allocation-decis', 'question', 'medium', 'G. Future funds, SPVs, and allocations', 'Will LPAC approval be needed for certain conflicts or allocation decisions', 'Will LPAC approval be needed for certain conflicts or allocation decisions?', 'Reserve LPAC approval for genuine conflicts (affiliate transactions, warehousing outside pre-agreed terms, allocation exceptions) and keep routine execution GP-discretionary. Settle the LPAC''s composition at the same time: the form brackets member count and appointment mechanics, and since the LPAC will carry real weight here (whitelist changes, warehousing, conflicts), keep it small (3-5 GP-appointed members from the largest LPs) and define its approval list precisely.', null, 'Open-items memo - Section 3 detailed questions', '["multi-clause"]'::jsonb, 71),
  ('q-069-will-the-manager-rely-on-an-investment-adviser-exemption-or-register', 'question', 'high', 'H. Regulatory, compliance, and operations', 'Will the manager rely on an investment adviser exemption or register', 'Will the manager rely on an investment adviser exemption or register?', 'Most sub-$150M private fund managers use the SEC private fund adviser exemption (ERA status) plus state rules. The answer drives compliance obligations across the platform.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 72),
  ('q-070-what-state-level-adviser-requirements-apply', 'question', 'medium', 'H. Regulatory, compliance, and operations', 'What state-level adviser requirements apply', 'What state-level adviser requirements apply?', 'Check the manager''s home state: some states require investment adviser registration even for exempt-reporting advisers.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 73),
  ('q-071-who-handles-aml-kyc-and-bad-actor-checks', 'question', 'medium', 'H. Regulatory, compliance, and operations', 'Who handles AML/KYC and bad actor checks', 'Who handles AML/KYC and bad actor checks?', 'Usually the fund administrator runs AML/KYC on subscriptions; Rule 506(d) bad-actor checks must also cover placement parties and beneficial owners of the GP.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 74),
  ('q-072-who-is-fund-administrator', 'question', 'medium', 'H. Regulatory, compliance, and operations', 'Who is fund administrator', 'Who is fund administrator?', 'Select early - the administrator drives capital-call logistics, reporting cadence, and AML/KYC workflow, and admin fees are a named Fund Expense.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 75),
  ('q-075-who-values-private-positions-and-spv-interests', 'question', 'high', 'H. Regulatory, compliance, and operations', 'Who values private positions and SPV interests', 'Who values private positions and SPV interests?', 'The GP values assets in good faith under the form, but stale secondary marks are a known regulator focus; adopt a written valuation policy covering indirect SPV positions and in-kind distributions.', null, 'Open-items memo - Section 3 detailed questions', '["fill-in"]'::jsonb, 76),
  ('q-076-what-cyber-privacy-data-room-procedures-are-needed', 'question', 'low', 'H. Regulatory, compliance, and operations', 'What cyber/privacy/data-room procedures are needed', 'What cyber/privacy/data-room procedures are needed?', 'Operational item: data-room access controls and investor-data handling belong in the compliance manual, not the fund documents.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 77),
  ('q-077-what-insurance-and-indemnity-coverage-should-be-maintained', 'question', 'medium', 'H. Regulatory, compliance, and operations', 'What insurance and indemnity coverage should be maintained', 'What insurance and indemnity coverage should be maintained?', 'GP/Manager D&O and E&O coverage backstops the fund indemnity; the form lets the fund bear the premium as a Fund Expense. Confirm the indemnity''s conduct standard too - the form exculpates absent material misconduct (vs a gross-negligence standard) - and whether covered persons extend to sourcing or placement parties, which LPs will resist.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 78),
  ('q-078-what-records-must-be-kept-for-placement-sourcing-investment-decisions-', 'question', 'low', 'H. Regulatory, compliance, and operations', 'What records must be kept for placement, sourcing, investment decisions, valuation, and conflicts', 'What records must be kept for placement, sourcing, investment decisions, valuation, and conflicts?', 'Keep contemporaneous files for solicitation, allocation, valuation, and conflicts decisions - these are the first documents requested in an exam or LP dispute.', null, 'Open-items memo - Section 3 detailed questions', '["high-level"]'::jsonb, 79),
  ('gap-005-amendment-consent-thresholds', 'question', 'medium', 'I. Fund lifecycle and governance (gap review)', 'Amendment consent thresholds', 'What LP consent threshold applies to amendments, and which amendments require special or affected-partner consent?', 'The form protects LPs from adverse amendments without consent. Confirm the general threshold (majority in interest is typical) and carve out administrative amendments the GP can make alone - important given the expected vehicle flexibility changes.', null, 'Term sheet gap review - not covered in the open-items memo', '["fill-in"]'::jsonb, 80),
  ('gap-006-side-letter-and-mfn-policy', 'question', 'medium', 'I. Fund lifecycle and governance (gap review)', 'Side letter and MFN policy', 'What side letter policy and MFN (most favored nation) rights will the fund offer?', 'The form permits side letters including better economics. Since placement arrangements and co-invest rights will live in side letters, decide MFN scope early (commonly size-tiered) so one LP''s deal doesn''t propagate to everyone.', null, 'Term sheet gap review - not covered in the open-items memo', '["addition-removal"]'::jsonb, 81),
  ('gap-007-subsequent-closing-true-up-and-interest', 'question', 'medium', 'I. Fund lifecycle and governance (gap review)', 'Subsequent-closing true-up and interest', 'Will subsequent-closing investors pay a true-up plus interest on their share of earlier capital calls and fees?', 'The form permits later closings within a bracketed window. With early warehoused deals, later investors will be buying into appreciated positions - decide the true-up interest rate and whether late LPs share in pre-closing deals at cost.', null, 'Term sheet gap review - not covered in the open-items memo', '["fill-in"]'::jsonb, 82),
  ('gap-008-recycling-and-reinvestment-of-proceeds', 'question', 'high', 'J. Distributions, liability, and tax (gap review)', 'Recycling and reinvestment of proceeds', 'May the fund recycle or reinvest disposition proceeds, and within what limits?', 'The memo never addresses recycling, but a secondaries fund with quick flips needs it: without reinvestment rights, early exits shrink deployable capital. Typical formulation permits recycling proceeds received during the investment period up to 100-120% of commitments.', null, 'Term sheet gap review - not covered in the open-items memo', '["addition-removal"]'::jsonb, 83),
  ('gap-009-in-kind-distributions-of-non-marketable-private-shares', 'question', 'high', 'J. Distributions, liability, and tax (gap review)', 'In-kind distributions of non-marketable private shares', 'Can the fund distribute non-marketable private shares in kind, and how are they valued and transferred given company ROFRs and consent rights?', 'The form only allows non-marketable in-kind distributions at dissolution. For a fund holding private secondaries, end-of-life positions may be unsaleable - the mechanics (valuation, ROFR compliance, LP election to decline) deserve real attention.', null, 'Term sheet gap review - not covered in the open-items memo', '["addition-removal"]'::jsonb, 84),
  ('gap-011-tax-exempt-and-non-u-s-investor-accommodations', 'question', 'medium', 'J. Distributions, liability, and tax (gap review)', 'Tax-exempt and non-U.S. investor accommodations', 'Will the fund accept tax-exempt or non-U.S. LPs, and are blockers or feeders needed for UBTI/ECI concerns?', 'Fund-level borrowing (subscription line, bridge) can create UBTI for tax-exempt LPs; non-U.S. LPs care about ECI. Decide whether to offer a blocker/feeder or restrict the investor base, and stay under the 25% ERISA plan-asset threshold.', null, 'Term sheet gap review - not covered in the open-items memo', '["multi-clause"]'::jsonb, 85),
  ('doc-2-1-fund-lpa-fund-agreement', 'supporting-document', 'low', 'Supporting documents: core fund document', 'Core Fund Document: Fund LPA / Fund Agreement', 'Full governing agreement for the Fund LP.', 'Must authorize secondary strategy, capital calls, expenses, additional vehicles, conflicts, fees, carry, borrowing, and investment limitations.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","core-fund-document"]'::jsonb, 86),
  ('doc-2-2-subscription-agreement', 'supporting-document', 'low', 'Supporting documents: core fund document', 'Core Fund Document: Subscription Agreement', 'Investor commitments and representations.', 'Accredited investor / qualified purchaser status, bad actor, AML/KYC, tax forms, ERISA reps, side letter integration.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","core-fund-document"]'::jsonb, 87),
  ('doc-2-3-ppm-offering-memorandum', 'supporting-document', 'low', 'Supporting documents: core fund document', 'Core Fund Document: PPM / Offering Memorandum', 'Main disclosure document.', 'Should disclose strategy, secondary risks, placement/sourcing arrangements, conflicts, fees, carry, transfer restrictions, valuation uncertainty.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","core-fund-document"]'::jsonb, 88),
  ('doc-2-4-form-d-and-state-blue-sky-filings', 'supporting-document', 'low', 'Supporting documents: core fund document', 'Core Fund Document: Form D and state blue-sky filings', 'Securities notice filings after first sale.', 'Coordinate with counsel immediately after first investor becomes contractually committed.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","core-fund-document"]'::jsonb, 89),
  ('doc-2-5-side-letter-template', 'supporting-document', 'low', 'Supporting documents: core fund document', 'Core Fund Document: Side Letter Template', 'Special investor terms.', 'MFN, fee/carry discounts, reporting, transfer, co-investment, excuse rights, confidentiality.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","core-fund-document"]'::jsonb, 90),
  ('doc-3-1-gp-llc-operating-agreement', 'supporting-document', 'low', 'Supporting documents: sponsor / management document', 'Sponsor / Management Document: GP LLC Operating Agreement', 'Creates legal control of the fund and carry recipient if no CarryCo is used.', 'Must separate voting/control from economics if non-control parties receive carry.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","sponsor-management-document"]'::jsonb, 91),
  ('doc-3-2-manager-llc-operating-agreement', 'supporting-document', 'low', 'Supporting documents: sponsor / management document', 'Sponsor / Management Document: Manager LLC Operating Agreement', 'Ongoing management/advisory business.', 'Defines ownership of management fee profits, authority, expenses, employment/consulting, adviser registration implications.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","sponsor-management-document"]'::jsonb, 92),
  ('doc-3-3-investment-management-agreement', 'supporting-document', 'low', 'Supporting documents: sponsor / management document', 'Sponsor / Management Document: Investment Management Agreement', 'Fund/GP engages Manager to provide advisory/admin services.', 'Defines delegated authority, fees, reimbursements, termination, indemnity, compliance obligations.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","sponsor-management-document"]'::jsonb, 93),
  ('doc-3-4-sponsor-holdco-agreement-if-used', 'supporting-document', 'low', 'Supporting documents: sponsor / management document', 'Sponsor / Management Document: Sponsor HoldCo Agreement, if used', 'Platform-level ownership above Manager and possibly GP entities.', 'Only use if useful for long-term platform economics; avoid giving fund-specific economics accidentally across all funds.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","sponsor-management-document"]'::jsonb, 94),
  ('doc-3-5-fund-specific-carryco-sponsorco-agreement-if-used', 'supporting-document', 'low', 'Supporting documents: sponsor / management document', 'Sponsor / Management Document: Fund-specific CarryCo / SponsorCo Agreement, if used', 'Splits carry for a particular fund.', 'Useful for Class A voting control, Class B non-voting conditional carry, passive economics, vesting, forfeiture, clawback sharing.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","sponsor-management-document"]'::jsonb, 95),
  ('doc-4-1-registered-broker-dealer-placement-agreement', 'supporting-document', 'low', 'Supporting documents: placement / sourcing document', 'Placement / Sourcing Document: Registered Broker-Dealer Placement Agreement', 'For registered placement agents.', 'Compensation, tail, permitted investors, offering materials, compliance review, FINRA/SEC obligations, indemnity.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","placement-sourcing-document"]'::jsonb, 96),
  ('doc-4-2-generic-capital-formation-placement-agreement', 'supporting-document', 'low', 'Supporting documents: placement / sourcing document', 'Placement / Sourcing Document: Generic Capital Formation / Placement Agreement', 'Template for buy-side LP placement relationships.', 'Must be limited by securities-law compliance; specify no authority to bind the fund, no custody, no investment discretion.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","placement-sourcing-document"]'::jsonb, 97),
  ('doc-4-3-conditional-carry-participation-agreement', 'supporting-document', 'low', 'Supporting documents: placement / sourcing document', 'Placement / Sourcing Document: Conditional Carry Participation Agreement', 'Carry or economics based on capital commitments placed.', 'May reference GP/CarryCo operating agreement. Include vesting thresholds, accepted commitments, tail, forfeiture, compliance conditions.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","placement-sourcing-document"]'::jsonb, 98),
  ('doc-4-4-finder-consultant-agreement', 'supporting-document', 'low', 'Supporting documents: placement / sourcing document', 'Placement / Sourcing Document: Finder / Consultant Agreement', 'Only for non-BD relationships if counsel approves.', 'Use carefully. Avoid transaction-based compensation unless counsel confirms path. Include reps and limitations.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","placement-sourcing-document"]'::jsonb, 99),
  ('doc-4-5-sell-side-sourcing-origination-agreement', 'supporting-document', 'low', 'Supporting documents: placement / sourcing document', 'Placement / Sourcing Document: Sell-Side Sourcing / Origination Agreement', 'For deal sources, brokers, consultants, or strategic relationships.', 'Define introduction-only vs negotiation role; compensation; exclusivity; confidentiality; no authority to bind fund.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","placement-sourcing-document"]'::jsonb, 100),
  ('doc-4-6-secondary-transaction-broker-agreement', 'supporting-document', 'low', 'Supporting documents: placement / sourcing document', 'Placement / Sourcing Document: Secondary Transaction / Broker Agreement', 'For parties helping acquire or dispose of private securities.', 'Broker-dealer analysis likely needed if compensation is transaction-based or party negotiates securities transactions.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","placement-sourcing-document"]'::jsonb, 101),
  ('doc-5-1-investment-policy-whitelist-schedule', 'supporting-document', 'low', 'Supporting documents: operating policy / process', 'Operating Policy / Process: Investment Policy / Whitelist Schedule', 'Defines eligible companies and permitted instruments.', 'Include update process for whitelist and approval thresholds.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","operating-policy-process"]'::jsonb, 102),
  ('doc-5-2-allocation-policy', 'supporting-document', 'low', 'Supporting documents: operating policy / process', 'Operating Policy / Process: Allocation Policy', 'Allocates opportunities among fund, co-invests, SPVs, parallel funds, affiliates, and future funds.', 'Critical if multiple inbound deal sources and LP-facing channels exist.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","operating-policy-process"]'::jsonb, 103),
  ('doc-5-3-capital-call-policy', 'supporting-document', 'low', 'Supporting documents: operating policy / process', 'Operating Policy / Process: Capital Call Policy', 'Normal and expedited capital-call procedures.', 'Should handle 3-5 business day calls, emergency calls, reserves, default penalties.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","operating-policy-process"]'::jsonb, 104),
  ('doc-5-4-warehousing-policy', 'supporting-document', 'low', 'Supporting documents: operating policy / process', 'Operating Policy / Process: Warehousing Policy', 'Permits GP/affiliate to warehouse deals before fund takes them down.', 'Define cost basis, expenses, timing, conflict approvals, disclosure.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","operating-policy-process"]'::jsonb, 105),
  ('doc-5-5-conflict-policy', 'supporting-document', 'low', 'Supporting documents: operating policy / process', 'Operating Policy / Process: Conflict Policy', 'Deals with affiliate transactions, sourced deals, side letters, co-invests, valuation, allocation.', 'Coordinate with LPAC provisions.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","operating-policy-process"]'::jsonb, 106),
  ('doc-5-6-valuation-policy', 'supporting-document', 'low', 'Supporting documents: operating policy / process', 'Operating Policy / Process: Valuation Policy', 'Valuation of private shares, SPVs, tender interests, forwards, and in-kind distributions.', 'Important due to illiquidity and limited observable prices.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","operating-policy-process"]'::jsonb, 107),
  ('doc-5-7-compliance-policies', 'supporting-document', 'low', 'Supporting documents: operating policy / process', 'Operating Policy / Process: Compliance Policies', 'Adviser, broker-dealer interface, AML/KYC, bad actor, privacy, records.', 'Depends on adviser registration/exemption and placement model.', null, 'Open-items memo - Section 1 additional documents needed', '["supporting-document","operating-policy-process"]'::jsonb, 108);

create temporary table seed_issue_sections (
  issue_stable_key text not null,
  section_stable_key text not null,
  position integer not null
) on commit drop;

insert into seed_issue_sections (issue_stable_key, section_stable_key, position) values
  ('decision-1-use-separate-carryco', 'sec-24-distributions', 0),
  ('decision-1-use-separate-carryco', 'sec-26-general-partner-clawback', 1),
  ('decision-1-use-separate-carryco', 'sec-08-management', 2),
  ('decision-1-use-separate-carryco', 'sec-09-sponsor-capital-commitment', 3),
  ('decision-2-who-owns-manager-llc', 'sec-08-management', 0),
  ('decision-2-who-owns-manager-llc', 'sec-10-management-fee', 1),
  ('decision-3-fund-exemption-path', 'sec-06-investor-qualifications', 0),
  ('decision-4-offering-path', 'sec-06-investor-qualifications', 0),
  ('decision-4-offering-path', 'sec-46-general-risks', 1),
  ('decision-5-capital-call-design', 'sec-21-capital-contributions', 0),
  ('decision-5-capital-call-design', 'sec-30-borrowing', 1),
  ('decision-5-capital-call-design', 'sec-23-warehoused-securities', 2),
  ('decision-6-vehicle-flexibility', 'sec-03-investment-objectives-and-program', 0),
  ('decision-6-vehicle-flexibility', 'sec-20-investment-limitations', 1),
  ('decision-6-vehicle-flexibility', 'sec-36-holding-vehicles-feeder-vehicle-alternative-investment-vehicles-parall', 2),
  ('decision-7-placement-compensation-disclosure', 'sec-11-management-fee-offset', 0),
  ('decision-7-placement-compensation-disclosure', 'sec-27-fund-expenses', 1),
  ('decision-7-placement-compensation-disclosure', 'sec-42-side-letters', 2),
  ('decision-7-placement-compensation-disclosure', 'sec-46-general-risks', 3),
  ('decision-8-successor-fund-restriction', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('decision-8-successor-fund-restriction', 'sec-34-co-investment-opportunities', 1),
  ('change-01-ability-to-give-conditional-carry-or-incentive-payments', 'sec-24-distributions', 0),
  ('change-01-ability-to-give-conditional-carry-or-incentive-payments', 'sec-11-management-fee-offset', 1),
  ('change-01-ability-to-give-conditional-carry-or-incentive-payments', 'sec-27-fund-expenses', 2),
  ('change-01-ability-to-give-conditional-carry-or-incentive-payments', 'sec-26-general-partner-clawback', 3),
  ('change-02-sourcing-origination-and-strategic-relationship-arrangements', 'sec-08-management', 0),
  ('change-02-sourcing-origination-and-strategic-relationship-arrangements', 'sec-27-fund-expenses', 1),
  ('change-02-sourcing-origination-and-strategic-relationship-arrangements', 'sec-29-other-competitive-activity-successor-fund', 2),
  ('change-02-sourcing-origination-and-strategic-relationship-arrangements', 'sec-38-exculpation-and-indemnification', 3),
  ('change-03-investment-objectives-and-permitted-investments', 'sec-03-investment-objectives-and-program', 0),
  ('change-03-investment-objectives-and-permitted-investments', 'sec-20-investment-limitations', 1),
  ('change-04-restriction-on-blind-pool-fund-investments-carveouts-for-weird-vehicle', 'sec-20-investment-limitations', 0),
  ('change-04-restriction-on-blind-pool-fund-investments-carveouts-for-weird-vehicle', 'sec-36-holding-vehicles-feeder-vehicle-alternative-investment-vehicles-parall', 1),
  ('change-05-capital-call-timing-and-fast-execution-mechanics', 'sec-21-capital-contributions', 0),
  ('change-05-capital-call-timing-and-fast-execution-mechanics', 'sec-30-borrowing', 1),
  ('change-05-capital-call-timing-and-fast-execution-mechanics', 'sec-23-warehoused-securities', 2),
  ('change-05-capital-call-timing-and-fast-execution-mechanics', 'sec-22-failure-to-make-capital-contributions', 3),
  ('change-06-successor-funds-parallel-funds-co-invests-and-spv-carveouts', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('change-06-successor-funds-parallel-funds-co-invests-and-spv-carveouts', 'sec-34-co-investment-opportunities', 1),
  ('change-06-successor-funds-parallel-funds-co-invests-and-spv-carveouts', 'sec-36-holding-vehicles-feeder-vehicle-alternative-investment-vehicles-parall', 2),
  ('q-001-will-the-fund-be-a-delaware-lp-or-delaware-llc', 'sec-01-the-fund', 0),
  ('q-001-will-the-fund-be-a-delaware-lp-or-delaware-llc', 'sec-02-the-fund-agreement', 1),
  ('q-002-will-the-gp-be-fund-specific-for-each-fund', 'sec-08-management', 0),
  ('q-002-will-the-gp-be-fund-specific-for-each-fund', 'sec-01-the-fund', 1),
  ('q-003-will-there-be-a-single-platform-manager-llc-across-all-funds', 'sec-08-management', 0),
  ('q-003-will-there-be-a-single-platform-manager-llc-across-all-funds', 'sec-10-management-fee', 1),
  ('q-004-will-there-be-a-sponsor-holdco-above-the-manager-and-gp-entities', 'sec-08-management', 0),
  ('q-005-do-we-need-a-fund-specific-carryco-sponsorco-or-can-carry-be-split-in-', 'sec-24-distributions', 0),
  ('q-005-do-we-need-a-fund-specific-carryco-sponsorco-or-can-carry-be-split-in-', 'sec-26-general-partner-clawback', 1),
  ('q-005-do-we-need-a-fund-specific-carryco-sponsorco-or-can-carry-be-split-in-', 'sec-08-management', 2),
  ('q-006-if-carryco-is-used-does-it-own-the-gp-llc-or-merely-receive-carry-econ', 'sec-08-management', 0),
  ('q-006-if-carryco-is-used-does-it-own-the-gp-llc-or-merely-receive-carry-econ', 'sec-24-distributions', 1),
  ('q-007-who-has-voting-control-at-each-level-gp-manager-sponsor-holdco-carryco', 'sec-08-management', 0),
  ('q-007-who-has-voting-control-at-each-level-gp-manager-sponsor-holdco-carryco', 'sec-18-removal-of-the-general-partner', 1),
  ('q-008-can-non-voting-economic-participants-receive-carry-without-governance-', 'sec-24-distributions', 0),
  ('q-008-can-non-voting-economic-participants-receive-carry-without-governance-', 'sec-08-management', 1),
  ('q-009-how-are-clawback-obligations-allocated-among-ultimate-carry-recipients', 'sec-26-general-partner-clawback', 0),
  ('q-009-how-are-clawback-obligations-allocated-among-ultimate-carry-recipients', 'sec-24-distributions', 1),
  ('q-009-how-are-clawback-obligations-allocated-among-ultimate-carry-recipients', 'sec-39-limited-partner-giveback', 2),
  ('q-014-will-placement-fees-organization-expenses-transaction-fees-or-monitori', 'sec-11-management-fee-offset', 0),
  ('q-014-will-placement-fees-organization-expenses-transaction-fees-or-monitori', 'sec-10-management-fee', 1),
  ('q-014-will-placement-fees-organization-expenses-transaction-fees-or-monitori', 'sec-27-fund-expenses', 2),
  ('q-017-european-waterfall-or-deal-by-deal-waterfall', 'sec-24-distributions', 0),
  ('q-017-european-waterfall-or-deal-by-deal-waterfall', 'sec-26-general-partner-clawback', 1),
  ('q-019-what-is-the-gp-commitment-and-can-it-be-cashless-notes-warehoused-secu', 'sec-09-sponsor-capital-commitment', 0),
  ('q-019-what-is-the-gp-commitment-and-can-it-be-cashless-notes-warehoused-secu', 'sec-23-warehoused-securities', 1),
  ('q-019-what-is-the-gp-commitment-and-can-it-be-cashless-notes-warehoused-secu', 'sec-21-capital-contributions', 2),
  ('q-020-what-counts-as-a-late-stage-private-technology-company', 'sec-03-investment-objectives-and-program', 0),
  ('q-021-will-the-fund-be-limited-to-a-schedule-a-whitelist-of-companies', 'sec-03-investment-objectives-and-program', 0),
  ('q-021-will-the-fund-be-limited-to-a-schedule-a-whitelist-of-companies', 'sec-20-investment-limitations', 1),
  ('q-022-who-can-add-or-remove-whitelist-companies-and-with-what-approval', 'sec-20-investment-limitations', 0),
  ('q-022-who-can-add-or-remove-whitelist-companies-and-with-what-approval', 'sec-12-limited-partner-advisory-committee', 1),
  ('q-022-who-can-add-or-remove-whitelist-companies-and-with-what-approval', 'sec-41-amendments', 2),
  ('q-023-can-the-fund-invest-in-companies-outside-the-whitelist-with-lpac-or-ma', 'sec-20-investment-limitations', 0),
  ('q-023-can-the-fund-invest-in-companies-outside-the-whitelist-with-lpac-or-ma', 'sec-12-limited-partner-advisory-committee', 1),
  ('q-024-can-the-fund-invest-in-spv-interests-tender-vehicles-forward-contracts', 'sec-03-investment-objectives-and-program', 0),
  ('q-024-can-the-fund-invest-in-spv-interests-tender-vehicles-forward-contracts', 'sec-20-investment-limitations', 1),
  ('q-024-can-the-fund-invest-in-spv-interests-tender-vehicles-forward-contracts', 'sec-36-holding-vehicles-feeder-vehicle-alternative-investment-vehicles-parall', 2),
  ('q-025-can-the-fund-invest-in-non-u-s-companies-or-non-u-s-holding-structures', 'sec-03-investment-objectives-and-program', 0),
  ('q-025-can-the-fund-invest-in-non-u-s-companies-or-non-u-s-holding-structures', 'sec-36-holding-vehicles-feeder-vehicle-alternative-investment-vehicles-parall', 1),
  ('q-025-can-the-fund-invest-in-non-u-s-companies-or-non-u-s-holding-structures', 'sec-45-taxation', 2),
  ('q-027-will-the-fund-allow-follow-on-investments-after-the-investment-period', 'sec-14-investment-period', 0),
  ('q-027-will-the-fund-allow-follow-on-investments-after-the-investment-period', 'sec-20-investment-limitations', 1),
  ('q-028-will-there-be-sector-exclusions-or-esg-prohibited-activity-restriction', 'sec-20-investment-limitations', 0),
  ('q-029-how-should-transfer-restrictions-rofrs-company-consent-tender-rules-an', 'sec-46-general-risks', 0),
  ('q-029-how-should-transfer-restrictions-rofrs-company-consent-tender-rules-an', 'sec-03-investment-objectives-and-program', 1),
  ('q-029-how-should-transfer-restrictions-rofrs-company-consent-tender-rules-an', 'sec-32-valuation', 2),
  ('q-032-what-is-the-emergency-special-capital-call-notice-period-for-time-sens', 'sec-21-capital-contributions', 0),
  ('q-033-can-the-gp-call-capital-for-deposits-broken-deal-expenses-legal-dilige', 'sec-21-capital-contributions', 0),
  ('q-033-can-the-gp-call-capital-for-deposits-broken-deal-expenses-legal-dilige', 'sec-27-fund-expenses', 1),
  ('q-034-what-default-remedies-apply-if-an-lp-misses-a-capital-call', 'sec-22-failure-to-make-capital-contributions', 0),
  ('q-034-what-default-remedies-apply-if-an-lp-misses-a-capital-call', 'sec-21-capital-contributions', 1),
  ('q-035-can-the-fund-borrow-under-a-bridge-facility-or-subscription-line', 'sec-30-borrowing', 0),
  ('q-035-can-the-fund-borrow-under-a-bridge-facility-or-subscription-line', 'sec-36-holding-vehicles-feeder-vehicle-alternative-investment-vehicles-parall', 1),
  ('q-036-can-the-gp-or-affiliate-advance-funds-to-the-fund', 'sec-30-borrowing', 0),
  ('q-036-can-the-gp-or-affiliate-advance-funds-to-the-fund', 'sec-28-general-partner-expenses', 1),
  ('q-037-can-the-gp-or-affiliate-warehouse-securities-and-later-sell-them-to-th', 'sec-23-warehoused-securities', 0),
  ('q-037-can-the-gp-or-affiliate-warehouse-securities-and-later-sell-them-to-th', 'sec-09-sponsor-capital-commitment', 1),
  ('q-038-what-approvals-are-needed-for-warehoused-investments', 'sec-23-warehoused-securities', 0),
  ('q-038-what-approvals-are-needed-for-warehoused-investments', 'sec-12-limited-partner-advisory-committee', 1),
  ('q-038-what-approvals-are-needed-for-warehoused-investments', 'sec-20-investment-limitations', 2),
  ('q-039-how-are-warehousing-costs-interest-legal-fees-and-conflict-disclosures', 'sec-23-warehoused-securities', 0),
  ('q-039-how-are-warehousing-costs-interest-legal-fees-and-conflict-disclosures', 'sec-27-fund-expenses', 1),
  ('q-040-who-can-solicit-lps', 'sec-06-investor-qualifications', 0),
  ('q-040-who-can-solicit-lps', 'sec-46-general-risks', 1),
  ('q-041-must-any-compensated-lp-placement-be-through-a-registered-broker-deale', 'sec-06-investor-qualifications', 0),
  ('q-042-can-non-bd-finders-or-consultants-be-used-and-under-what-restrictions', 'sec-06-investor-qualifications', 0),
  ('q-043-can-placement-compensation-include-cash-fees-management-fee-sharing-ca', 'sec-11-management-fee-offset', 0),
  ('q-043-can-placement-compensation-include-cash-fees-management-fee-sharing-ca', 'sec-27-fund-expenses', 1),
  ('q-043-can-placement-compensation-include-cash-fees-management-fee-sharing-ca', 'sec-24-distributions', 2),
  ('q-044-is-compensation-paid-by-the-fund-gp-manager-carryco-or-affiliate', 'sec-27-fund-expenses', 0),
  ('q-044-is-compensation-paid-by-the-fund-gp-manager-carryco-or-affiliate', 'sec-28-general-partner-expenses', 1),
  ('q-044-is-compensation-paid-by-the-fund-gp-manager-carryco-or-affiliate', 'sec-11-management-fee-offset', 2),
  ('q-045-is-the-compensation-treated-as-fund-expense-manager-expense-or-gp-carr', 'sec-27-fund-expenses', 0),
  ('q-045-is-the-compensation-treated-as-fund-expense-manager-expense-or-gp-carr', 'sec-11-management-fee-offset', 1),
  ('q-046-will-placement-linked-carry-require-disclosure-in-the-ppm-and-or-term-', 'sec-46-general-risks', 0),
  ('q-046-will-placement-linked-carry-require-disclosure-in-the-ppm-and-or-term-', 'sec-42-side-letters', 1),
  ('q-047-will-placement-parties-receive-a-tail-on-lps-introduced-before-termina', 'sec-27-fund-expenses', 0),
  ('q-048-who-approves-offering-materials-and-investor-communications', 'sec-08-management', 0),
  ('q-048-who-approves-offering-materials-and-investor-communications', 'sec-06-investor-qualifications', 1),
  ('q-049-how-will-506-b-relationship-rules-or-506-c-verification-rules-be-handl', 'sec-06-investor-qualifications', 0),
  ('q-049-how-will-506-b-relationship-rules-or-506-c-verification-rules-be-handl', 'sec-46-general-risks', 1),
  ('q-050-who-can-source-secondary-opportunities', 'sec-08-management', 0),
  ('q-050-who-can-source-secondary-opportunities', 'sec-03-investment-objectives-and-program', 1),
  ('q-051-can-sourcing-parties-receive-cash-fees-deal-by-deal-carry-fund-carry-o', 'sec-27-fund-expenses', 0),
  ('q-051-can-sourcing-parties-receive-cash-fees-deal-by-deal-carry-fund-carry-o', 'sec-24-distributions', 1),
  ('q-051-can-sourcing-parties-receive-cash-fees-deal-by-deal-carry-fund-carry-o', 'sec-11-management-fee-offset', 2),
  ('q-052-can-a-deal-source-negotiate-terms-or-only-introduce-opportunities', 'sec-08-management', 0),
  ('q-053-can-a-deal-source-also-represent-sellers', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('q-053-can-a-deal-source-also-represent-sellers', 'sec-38-exculpation-and-indemnification', 1),
  ('q-054-do-deal-source-payments-create-broker-dealer-concerns', 'sec-46-general-risks', 0),
  ('q-055-are-sourcing-fees-fund-expenses-or-manager-gp-expenses', 'sec-27-fund-expenses', 0),
  ('q-055-are-sourcing-fees-fund-expenses-or-manager-gp-expenses', 'sec-28-general-partner-expenses', 1),
  ('q-056-are-there-exclusivity-non-circumvention-or-tail-periods', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('q-057-what-disclosures-are-required-for-affiliated-or-related-party-sourcing', 'sec-20-investment-limitations', 0),
  ('q-057-what-disclosures-are-required-for-affiliated-or-related-party-sourcing', 'sec-46-general-risks', 1),
  ('q-058-how-are-conflicts-handled-if-a-source-also-participates-in-another-veh', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('q-058-how-are-conflicts-handled-if-a-source-also-participates-in-another-veh', 'sec-34-co-investment-opportunities', 1),
  ('q-059-who-has-authority-to-approve-sourced-deals', 'sec-08-management', 0),
  ('q-059-who-has-authority-to-approve-sourced-deals', 'sec-12-limited-partner-advisory-committee', 1),
  ('q-060-when-can-a-successor-fund-be-launched', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('q-061-what-counts-as-a-prohibited-substantially-similar-blind-pool-fund', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('q-062-what-carveouts-are-needed-for-co-invest-vehicles-single-deal-spvs-feed', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('q-062-what-carveouts-are-needed-for-co-invest-vehicles-single-deal-spvs-feed', 'sec-36-holding-vehicles-feeder-vehicle-alternative-investment-vehicles-parall', 1),
  ('q-062-what-carveouts-are-needed-for-co-invest-vehicles-single-deal-spvs-feed', 'sec-34-co-investment-opportunities', 2),
  ('q-063-can-the-manager-manage-multiple-funds-at-once', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('q-063-can-the-manager-manage-multiple-funds-at-once', 'sec-08-management', 1),
  ('q-064-how-are-opportunities-allocated-among-fund-i-fund-ii-co-invests-parall', 'sec-29-other-competitive-activity-successor-fund', 0),
  ('q-064-how-are-opportunities-allocated-among-fund-i-fund-ii-co-invests-parall', 'sec-34-co-investment-opportunities', 1),
  ('q-065-can-lps-get-co-investment-rights', 'sec-34-co-investment-opportunities', 0),
  ('q-065-can-lps-get-co-investment-rights', 'sec-42-side-letters', 1),
  ('q-066-can-insiders-invest-personally-alongside-the-fund', 'sec-34-co-investment-opportunities', 0),
  ('q-066-can-insiders-invest-personally-alongside-the-fund', 'sec-20-investment-limitations', 1),
  ('q-067-can-the-fund-invest-through-a-vehicle-that-charges-its-own-fees-carry', 'sec-20-investment-limitations', 0),
  ('q-067-can-the-fund-invest-through-a-vehicle-that-charges-its-own-fees-carry', 'sec-36-holding-vehicles-feeder-vehicle-alternative-investment-vehicles-parall', 1),
  ('q-068-will-lpac-approval-be-needed-for-certain-conflicts-or-allocation-decis', 'sec-12-limited-partner-advisory-committee', 0),
  ('q-068-will-lpac-approval-be-needed-for-certain-conflicts-or-allocation-decis', 'sec-20-investment-limitations', 1),
  ('q-069-will-the-manager-rely-on-an-investment-adviser-exemption-or-register', 'sec-08-management', 0),
  ('q-069-will-the-manager-rely-on-an-investment-adviser-exemption-or-register', 'sec-46-general-risks', 1),
  ('q-070-what-state-level-adviser-requirements-apply', 'sec-08-management', 0),
  ('q-071-who-handles-aml-kyc-and-bad-actor-checks', 'sec-06-investor-qualifications', 0),
  ('q-072-who-is-fund-administrator', 'sec-31-reports', 0),
  ('q-072-who-is-fund-administrator', 'sec-27-fund-expenses', 1),
  ('q-075-who-values-private-positions-and-spv-interests', 'sec-32-valuation', 0),
  ('q-075-who-values-private-positions-and-spv-interests', 'sec-25-in-kind-distributions', 1),
  ('q-076-what-cyber-privacy-data-room-procedures-are-needed', 'sec-31-reports', 0),
  ('q-077-what-insurance-and-indemnity-coverage-should-be-maintained', 'sec-38-exculpation-and-indemnification', 0),
  ('q-077-what-insurance-and-indemnity-coverage-should-be-maintained', 'sec-27-fund-expenses', 1),
  ('q-078-what-records-must-be-kept-for-placement-sourcing-investment-decisions-', 'sec-31-reports', 0),
  ('q-078-what-records-must-be-kept-for-placement-sourcing-investment-decisions-', 'sec-08-management', 1),
  ('gap-005-amendment-consent-thresholds', 'sec-41-amendments', 0),
  ('gap-005-amendment-consent-thresholds', 'sec-12-limited-partner-advisory-committee', 1),
  ('gap-006-side-letter-and-mfn-policy', 'sec-42-side-letters', 0),
  ('gap-006-side-letter-and-mfn-policy', 'sec-06-investor-qualifications', 1),
  ('gap-007-subsequent-closing-true-up-and-interest', 'sec-05-closings', 0),
  ('gap-007-subsequent-closing-true-up-and-interest', 'sec-21-capital-contributions', 1),
  ('gap-008-recycling-and-reinvestment-of-proceeds', 'sec-24-distributions', 0),
  ('gap-008-recycling-and-reinvestment-of-proceeds', 'sec-14-investment-period', 1),
  ('gap-009-in-kind-distributions-of-non-marketable-private-shares', 'sec-25-in-kind-distributions', 0),
  ('gap-009-in-kind-distributions-of-non-marketable-private-shares', 'sec-32-valuation', 1),
  ('gap-009-in-kind-distributions-of-non-marketable-private-shares', 'sec-16-dissolution', 2),
  ('gap-011-tax-exempt-and-non-u-s-investor-accommodations', 'sec-45-taxation', 0),
  ('gap-011-tax-exempt-and-non-u-s-investor-accommodations', 'sec-40-erisa', 1),
  ('gap-011-tax-exempt-and-non-u-s-investor-accommodations', 'sec-36-holding-vehicles-feeder-vehicle-alternative-investment-vehicles-parall', 2),
  ('doc-2-1-fund-lpa-fund-agreement', 'sec-02-the-fund-agreement', 0),
  ('doc-2-2-subscription-agreement', 'sec-06-investor-qualifications', 0),
  ('doc-2-2-subscription-agreement', 'sec-05-closings', 1),
  ('doc-2-3-ppm-offering-memorandum', 'sec-46-general-risks', 0),
  ('doc-2-3-ppm-offering-memorandum', 'sec-03-investment-objectives-and-program', 1),
  ('doc-2-4-form-d-and-state-blue-sky-filings', 'sec-06-investor-qualifications', 0),
  ('doc-2-5-side-letter-template', 'sec-42-side-letters', 0),
  ('doc-3-1-gp-llc-operating-agreement', 'sec-08-management', 0),
  ('doc-3-1-gp-llc-operating-agreement', 'sec-24-distributions', 1),
  ('doc-3-1-gp-llc-operating-agreement', 'sec-26-general-partner-clawback', 2),
  ('doc-3-2-manager-llc-operating-agreement', 'sec-08-management', 0),
  ('doc-3-2-manager-llc-operating-agreement', 'sec-10-management-fee', 1),
  ('doc-3-3-investment-management-agreement', 'sec-08-management', 0),
  ('doc-3-3-investment-management-agreement', 'sec-10-management-fee', 1),
  ('doc-3-4-sponsor-holdco-agreement-if-used', 'sec-08-management', 0),
  ('doc-3-5-fund-specific-carryco-sponsorco-agreement-if-used', 'sec-24-distributions', 0),
  ('doc-3-5-fund-specific-carryco-sponsorco-agreement-if-used', 'sec-26-general-partner-clawback', 1),
  ('doc-3-5-fund-specific-carryco-sponsorco-agreement-if-used', 'sec-08-management', 2),
  ('doc-4-1-registered-broker-dealer-placement-agreement', 'sec-06-investor-qualifications', 0),
  ('doc-4-1-registered-broker-dealer-placement-agreement', 'sec-27-fund-expenses', 1),
  ('doc-4-2-generic-capital-formation-placement-agreement', 'sec-06-investor-qualifications', 0),
  ('doc-4-2-generic-capital-formation-placement-agreement', 'sec-27-fund-expenses', 1),
  ('doc-4-2-generic-capital-formation-placement-agreement', 'sec-11-management-fee-offset', 2),
  ('doc-4-3-conditional-carry-participation-agreement', 'sec-24-distributions', 0),
  ('doc-4-3-conditional-carry-participation-agreement', 'sec-26-general-partner-clawback', 1),
  ('doc-4-4-finder-consultant-agreement', 'sec-06-investor-qualifications', 0),
  ('doc-4-4-finder-consultant-agreement', 'sec-46-general-risks', 1),
  ('doc-4-5-sell-side-sourcing-origination-agreement', 'sec-27-fund-expenses', 0),
  ('doc-4-5-sell-side-sourcing-origination-agreement', 'sec-29-other-competitive-activity-successor-fund', 1),
  ('doc-4-6-secondary-transaction-broker-agreement', 'sec-03-investment-objectives-and-program', 0),
  ('doc-4-6-secondary-transaction-broker-agreement', 'sec-33-transfers-of-interests-and-withdrawals', 1),
  ('doc-5-1-investment-policy-whitelist-schedule', 'sec-03-investment-objectives-and-program', 0),
  ('doc-5-1-investment-policy-whitelist-schedule', 'sec-20-investment-limitations', 1),
  ('doc-5-2-allocation-policy', 'sec-34-co-investment-opportunities', 0),
  ('doc-5-2-allocation-policy', 'sec-29-other-competitive-activity-successor-fund', 1),
  ('doc-5-3-capital-call-policy', 'sec-21-capital-contributions', 0),
  ('doc-5-4-warehousing-policy', 'sec-23-warehoused-securities', 0),
  ('doc-5-4-warehousing-policy', 'sec-12-limited-partner-advisory-committee', 1),
  ('doc-5-5-conflict-policy', 'sec-20-investment-limitations', 0),
  ('doc-5-5-conflict-policy', 'sec-12-limited-partner-advisory-committee', 1),
  ('doc-5-5-conflict-policy', 'sec-29-other-competitive-activity-successor-fund', 2),
  ('doc-5-6-valuation-policy', 'sec-32-valuation', 0),
  ('doc-5-6-valuation-policy', 'sec-25-in-kind-distributions', 1),
  ('doc-5-7-compliance-policies', 'sec-06-investor-qualifications', 0),
  ('doc-5-7-compliance-policies', 'sec-31-reports', 1);

-- 1a. Before removing retired seed issues, preserve any user answers/notes on
--     them as clause notes on their primary linked clause (the retired
--     fill-in questions are replaced by the clause-election editor).
insert into public.clause_states (section_id, project_id, notes)
select ls.section_id,
       i.project_id,
       string_agg(
         'From retired question "' || i.title || '": '
           || trim(coalesce(st.answer, '')
           || case when coalesce(st.owner_note, '') <> '' then e'
' || st.owner_note else '' end
           || case when coalesce(st.follow_up_notes, '') <> '' then e'
' || st.follow_up_notes else '' end),
         e'

'
       )
from public.issues i
join public.issue_states st on st.issue_id = i.id
join lateral (
  select x.section_id from public.issue_sections x
  where x.issue_id = i.id
  order by x.position
  limit 1
) ls on true
where i.stable_key ~ '^(q|gap|decision|change|doc|check)-'
  and not exists (select 1 from seed_issues s where s.stable_key = i.stable_key)
  and (coalesce(st.answer, '') <> '' or coalesce(st.owner_note, '') <> '' or coalesce(st.follow_up_notes, '') <> '')
group by ls.section_id, i.project_id
on conflict (section_id) do update
  set notes = case
    when coalesce(public.clause_states.notes, '') = '' then excluded.notes
    else public.clause_states.notes || e'

' || excluded.notes
  end;

-- 1b. Remove seeded issues that are no longer part of the seed (retired
--     fill-in questions and checklist items). Cascades clean up their
--     links/states/events.
delete from public.issues i
where i.stable_key ~ '^(q|gap|decision|change|doc|check)-'
  and not exists (select 1 from seed_issues s where s.stable_key = i.stable_key);

-- 2. Update surviving seeded issues in place; issue_states (user answers) are
--    keyed by issue id and remain untouched.
update public.issues i
set issue_type = s.issue_type,
    priority = s.priority,
    category = s.category,
    title = s.title,
    prompt = s.prompt,
    details = s.details,
    provisional_answer = s.provisional_answer,
    source_label = s.source_label,
    tags = s.tags,
    sort_order = s.sort_order
from seed_issues s
where i.stable_key = s.stable_key;

-- 3. Insert seed issues that seeded projects are missing (new gap questions).
--    The create_initial_issue_state trigger creates their issue_states rows.
insert into public.issues (
  project_id, stable_key, issue_type, initial_status, priority, category,
  title, prompt, details, provisional_answer, source_label, tags, sort_order, created_by
)
select p.id, s.stable_key, s.issue_type, 'open', s.priority, s.category,
       s.title, s.prompt, s.details, s.provisional_answer, s.source_label, s.tags, s.sort_order, p.created_by
from public.projects p
cross join seed_issues s
where exists (
    select 1 from public.issues i
    where i.project_id = p.id and i.stable_key ~ '^(q|gap|decision|change|doc|check)-'
  )
  and not exists (
    select 1 from public.issues i
    where i.project_id = p.id and i.stable_key = s.stable_key
  );

-- 4. Rebuild clause links for all seeded issues from the curated assignments.
delete from public.issue_sections ls
using public.issues i
where ls.issue_id = i.id
  and i.stable_key in (select stable_key from seed_issues);

insert into public.issue_sections (project_id, issue_id, section_id, position)
select i.project_id, i.id, ds.id, l.position
from seed_issue_sections l
join public.issues i on i.stable_key = l.issue_stable_key
join public.document_sections ds
  on ds.project_id = i.project_id and ds.stable_key = l.section_stable_key;

commit;
